# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yhs_can_msgs/steering_ctrl_cmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class steering_ctrl_cmd(genpy.Message):
  _md5sum = "b8e9d8788608c044b8a724447419e8d0"
  _type = "yhs_can_msgs/steering_ctrl_cmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8    ctrl_cmd_gear
float32  steering_ctrl_cmd_velocity
float32  steering_ctrl_cmd_steering
"""
  __slots__ = ['ctrl_cmd_gear','steering_ctrl_cmd_velocity','steering_ctrl_cmd_steering']
  _slot_types = ['uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ctrl_cmd_gear,steering_ctrl_cmd_velocity,steering_ctrl_cmd_steering

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(steering_ctrl_cmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ctrl_cmd_gear is None:
        self.ctrl_cmd_gear = 0
      if self.steering_ctrl_cmd_velocity is None:
        self.steering_ctrl_cmd_velocity = 0.
      if self.steering_ctrl_cmd_steering is None:
        self.steering_ctrl_cmd_steering = 0.
    else:
      self.ctrl_cmd_gear = 0
      self.steering_ctrl_cmd_velocity = 0.
      self.steering_ctrl_cmd_steering = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.ctrl_cmd_gear, _x.steering_ctrl_cmd_velocity, _x.steering_ctrl_cmd_steering))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.ctrl_cmd_gear, _x.steering_ctrl_cmd_velocity, _x.steering_ctrl_cmd_steering,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.ctrl_cmd_gear, _x.steering_ctrl_cmd_velocity, _x.steering_ctrl_cmd_steering))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.ctrl_cmd_gear, _x.steering_ctrl_cmd_velocity, _x.steering_ctrl_cmd_steering,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2f = None
def _get_struct_B2f():
    global _struct_B2f
    if _struct_B2f is None:
        _struct_B2f = struct.Struct("<B2f")
    return _struct_B2f
