# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yhs_can_msgs/ctrl_cmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ctrl_cmd(genpy.Message):
  _md5sum = "e0a0e35016e404c7e4386a62c7a595e7"
  _type = "yhs_can_msgs/ctrl_cmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8    ctrl_cmd_gear
float32  ctrl_cmd_x_linear
float32  ctrl_cmd_z_angular
float32  ctrl_cmd_y_linear
"""
  __slots__ = ['ctrl_cmd_gear','ctrl_cmd_x_linear','ctrl_cmd_z_angular','ctrl_cmd_y_linear']
  _slot_types = ['uint8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ctrl_cmd_gear,ctrl_cmd_x_linear,ctrl_cmd_z_angular,ctrl_cmd_y_linear

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ctrl_cmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ctrl_cmd_gear is None:
        self.ctrl_cmd_gear = 0
      if self.ctrl_cmd_x_linear is None:
        self.ctrl_cmd_x_linear = 0.
      if self.ctrl_cmd_z_angular is None:
        self.ctrl_cmd_z_angular = 0.
      if self.ctrl_cmd_y_linear is None:
        self.ctrl_cmd_y_linear = 0.
    else:
      self.ctrl_cmd_gear = 0
      self.ctrl_cmd_x_linear = 0.
      self.ctrl_cmd_z_angular = 0.
      self.ctrl_cmd_y_linear = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.ctrl_cmd_gear, _x.ctrl_cmd_x_linear, _x.ctrl_cmd_z_angular, _x.ctrl_cmd_y_linear))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.ctrl_cmd_gear, _x.ctrl_cmd_x_linear, _x.ctrl_cmd_z_angular, _x.ctrl_cmd_y_linear,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.ctrl_cmd_gear, _x.ctrl_cmd_x_linear, _x.ctrl_cmd_z_angular, _x.ctrl_cmd_y_linear))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.ctrl_cmd_gear, _x.ctrl_cmd_x_linear, _x.ctrl_cmd_z_angular, _x.ctrl_cmd_y_linear,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3f = None
def _get_struct_B3f():
    global _struct_B3f
    if _struct_B3f is None:
        _struct_B3f = struct.Struct("<B3f")
    return _struct_B3f
