# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yhs_can_msgs/io_fb.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class io_fb(genpy.Message):
  _md5sum = "734f5c2c489a056cd36d8e25d62c72df"
  _type = "yhs_can_msgs/io_fb"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool  io_fb_lamp_ctrl
bool  io_fb_unlock
bool  io_fb_lower_beam_headlamp
bool  io_fb_upper_beam_headlamp
int8  io_fb_turn_lamp
bool  io_fb_braking_lamp
bool  io_fb_clearance_lamp
bool  io_fb_fog_lamp
bool  io_fb_speaker
bool  io_fb_fl_impact_sensor
bool  io_fb_fm_impact_sensor
bool  io_fb_fr_impact_sensor
bool  io_fb_rl_impact_sensor
bool  io_fb_rm_impact_sensor
bool  io_fb_rr_impact_sensor
bool  io_fb_fl_drop_sensor
bool  io_fb_fm_drop_sensor
bool  io_fb_fr_drop_sensor
bool  io_fb_rl_drop_sensor
bool  io_fb_rm_drop_sensor
bool  io_fb_rr_drop_sensor
bool  io_fb_estop
bool  io_fb_joypad_ctrl
bool  io_fb_charge_state
"""
  __slots__ = ['io_fb_lamp_ctrl','io_fb_unlock','io_fb_lower_beam_headlamp','io_fb_upper_beam_headlamp','io_fb_turn_lamp','io_fb_braking_lamp','io_fb_clearance_lamp','io_fb_fog_lamp','io_fb_speaker','io_fb_fl_impact_sensor','io_fb_fm_impact_sensor','io_fb_fr_impact_sensor','io_fb_rl_impact_sensor','io_fb_rm_impact_sensor','io_fb_rr_impact_sensor','io_fb_fl_drop_sensor','io_fb_fm_drop_sensor','io_fb_fr_drop_sensor','io_fb_rl_drop_sensor','io_fb_rm_drop_sensor','io_fb_rr_drop_sensor','io_fb_estop','io_fb_joypad_ctrl','io_fb_charge_state']
  _slot_types = ['bool','bool','bool','bool','int8','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       io_fb_lamp_ctrl,io_fb_unlock,io_fb_lower_beam_headlamp,io_fb_upper_beam_headlamp,io_fb_turn_lamp,io_fb_braking_lamp,io_fb_clearance_lamp,io_fb_fog_lamp,io_fb_speaker,io_fb_fl_impact_sensor,io_fb_fm_impact_sensor,io_fb_fr_impact_sensor,io_fb_rl_impact_sensor,io_fb_rm_impact_sensor,io_fb_rr_impact_sensor,io_fb_fl_drop_sensor,io_fb_fm_drop_sensor,io_fb_fr_drop_sensor,io_fb_rl_drop_sensor,io_fb_rm_drop_sensor,io_fb_rr_drop_sensor,io_fb_estop,io_fb_joypad_ctrl,io_fb_charge_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(io_fb, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.io_fb_lamp_ctrl is None:
        self.io_fb_lamp_ctrl = False
      if self.io_fb_unlock is None:
        self.io_fb_unlock = False
      if self.io_fb_lower_beam_headlamp is None:
        self.io_fb_lower_beam_headlamp = False
      if self.io_fb_upper_beam_headlamp is None:
        self.io_fb_upper_beam_headlamp = False
      if self.io_fb_turn_lamp is None:
        self.io_fb_turn_lamp = 0
      if self.io_fb_braking_lamp is None:
        self.io_fb_braking_lamp = False
      if self.io_fb_clearance_lamp is None:
        self.io_fb_clearance_lamp = False
      if self.io_fb_fog_lamp is None:
        self.io_fb_fog_lamp = False
      if self.io_fb_speaker is None:
        self.io_fb_speaker = False
      if self.io_fb_fl_impact_sensor is None:
        self.io_fb_fl_impact_sensor = False
      if self.io_fb_fm_impact_sensor is None:
        self.io_fb_fm_impact_sensor = False
      if self.io_fb_fr_impact_sensor is None:
        self.io_fb_fr_impact_sensor = False
      if self.io_fb_rl_impact_sensor is None:
        self.io_fb_rl_impact_sensor = False
      if self.io_fb_rm_impact_sensor is None:
        self.io_fb_rm_impact_sensor = False
      if self.io_fb_rr_impact_sensor is None:
        self.io_fb_rr_impact_sensor = False
      if self.io_fb_fl_drop_sensor is None:
        self.io_fb_fl_drop_sensor = False
      if self.io_fb_fm_drop_sensor is None:
        self.io_fb_fm_drop_sensor = False
      if self.io_fb_fr_drop_sensor is None:
        self.io_fb_fr_drop_sensor = False
      if self.io_fb_rl_drop_sensor is None:
        self.io_fb_rl_drop_sensor = False
      if self.io_fb_rm_drop_sensor is None:
        self.io_fb_rm_drop_sensor = False
      if self.io_fb_rr_drop_sensor is None:
        self.io_fb_rr_drop_sensor = False
      if self.io_fb_estop is None:
        self.io_fb_estop = False
      if self.io_fb_joypad_ctrl is None:
        self.io_fb_joypad_ctrl = False
      if self.io_fb_charge_state is None:
        self.io_fb_charge_state = False
    else:
      self.io_fb_lamp_ctrl = False
      self.io_fb_unlock = False
      self.io_fb_lower_beam_headlamp = False
      self.io_fb_upper_beam_headlamp = False
      self.io_fb_turn_lamp = 0
      self.io_fb_braking_lamp = False
      self.io_fb_clearance_lamp = False
      self.io_fb_fog_lamp = False
      self.io_fb_speaker = False
      self.io_fb_fl_impact_sensor = False
      self.io_fb_fm_impact_sensor = False
      self.io_fb_fr_impact_sensor = False
      self.io_fb_rl_impact_sensor = False
      self.io_fb_rm_impact_sensor = False
      self.io_fb_rr_impact_sensor = False
      self.io_fb_fl_drop_sensor = False
      self.io_fb_fm_drop_sensor = False
      self.io_fb_fr_drop_sensor = False
      self.io_fb_rl_drop_sensor = False
      self.io_fb_rm_drop_sensor = False
      self.io_fb_rr_drop_sensor = False
      self.io_fb_estop = False
      self.io_fb_joypad_ctrl = False
      self.io_fb_charge_state = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4Bb19B().pack(_x.io_fb_lamp_ctrl, _x.io_fb_unlock, _x.io_fb_lower_beam_headlamp, _x.io_fb_upper_beam_headlamp, _x.io_fb_turn_lamp, _x.io_fb_braking_lamp, _x.io_fb_clearance_lamp, _x.io_fb_fog_lamp, _x.io_fb_speaker, _x.io_fb_fl_impact_sensor, _x.io_fb_fm_impact_sensor, _x.io_fb_fr_impact_sensor, _x.io_fb_rl_impact_sensor, _x.io_fb_rm_impact_sensor, _x.io_fb_rr_impact_sensor, _x.io_fb_fl_drop_sensor, _x.io_fb_fm_drop_sensor, _x.io_fb_fr_drop_sensor, _x.io_fb_rl_drop_sensor, _x.io_fb_rm_drop_sensor, _x.io_fb_rr_drop_sensor, _x.io_fb_estop, _x.io_fb_joypad_ctrl, _x.io_fb_charge_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.io_fb_lamp_ctrl, _x.io_fb_unlock, _x.io_fb_lower_beam_headlamp, _x.io_fb_upper_beam_headlamp, _x.io_fb_turn_lamp, _x.io_fb_braking_lamp, _x.io_fb_clearance_lamp, _x.io_fb_fog_lamp, _x.io_fb_speaker, _x.io_fb_fl_impact_sensor, _x.io_fb_fm_impact_sensor, _x.io_fb_fr_impact_sensor, _x.io_fb_rl_impact_sensor, _x.io_fb_rm_impact_sensor, _x.io_fb_rr_impact_sensor, _x.io_fb_fl_drop_sensor, _x.io_fb_fm_drop_sensor, _x.io_fb_fr_drop_sensor, _x.io_fb_rl_drop_sensor, _x.io_fb_rm_drop_sensor, _x.io_fb_rr_drop_sensor, _x.io_fb_estop, _x.io_fb_joypad_ctrl, _x.io_fb_charge_state,) = _get_struct_4Bb19B().unpack(str[start:end])
      self.io_fb_lamp_ctrl = bool(self.io_fb_lamp_ctrl)
      self.io_fb_unlock = bool(self.io_fb_unlock)
      self.io_fb_lower_beam_headlamp = bool(self.io_fb_lower_beam_headlamp)
      self.io_fb_upper_beam_headlamp = bool(self.io_fb_upper_beam_headlamp)
      self.io_fb_braking_lamp = bool(self.io_fb_braking_lamp)
      self.io_fb_clearance_lamp = bool(self.io_fb_clearance_lamp)
      self.io_fb_fog_lamp = bool(self.io_fb_fog_lamp)
      self.io_fb_speaker = bool(self.io_fb_speaker)
      self.io_fb_fl_impact_sensor = bool(self.io_fb_fl_impact_sensor)
      self.io_fb_fm_impact_sensor = bool(self.io_fb_fm_impact_sensor)
      self.io_fb_fr_impact_sensor = bool(self.io_fb_fr_impact_sensor)
      self.io_fb_rl_impact_sensor = bool(self.io_fb_rl_impact_sensor)
      self.io_fb_rm_impact_sensor = bool(self.io_fb_rm_impact_sensor)
      self.io_fb_rr_impact_sensor = bool(self.io_fb_rr_impact_sensor)
      self.io_fb_fl_drop_sensor = bool(self.io_fb_fl_drop_sensor)
      self.io_fb_fm_drop_sensor = bool(self.io_fb_fm_drop_sensor)
      self.io_fb_fr_drop_sensor = bool(self.io_fb_fr_drop_sensor)
      self.io_fb_rl_drop_sensor = bool(self.io_fb_rl_drop_sensor)
      self.io_fb_rm_drop_sensor = bool(self.io_fb_rm_drop_sensor)
      self.io_fb_rr_drop_sensor = bool(self.io_fb_rr_drop_sensor)
      self.io_fb_estop = bool(self.io_fb_estop)
      self.io_fb_joypad_ctrl = bool(self.io_fb_joypad_ctrl)
      self.io_fb_charge_state = bool(self.io_fb_charge_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4Bb19B().pack(_x.io_fb_lamp_ctrl, _x.io_fb_unlock, _x.io_fb_lower_beam_headlamp, _x.io_fb_upper_beam_headlamp, _x.io_fb_turn_lamp, _x.io_fb_braking_lamp, _x.io_fb_clearance_lamp, _x.io_fb_fog_lamp, _x.io_fb_speaker, _x.io_fb_fl_impact_sensor, _x.io_fb_fm_impact_sensor, _x.io_fb_fr_impact_sensor, _x.io_fb_rl_impact_sensor, _x.io_fb_rm_impact_sensor, _x.io_fb_rr_impact_sensor, _x.io_fb_fl_drop_sensor, _x.io_fb_fm_drop_sensor, _x.io_fb_fr_drop_sensor, _x.io_fb_rl_drop_sensor, _x.io_fb_rm_drop_sensor, _x.io_fb_rr_drop_sensor, _x.io_fb_estop, _x.io_fb_joypad_ctrl, _x.io_fb_charge_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.io_fb_lamp_ctrl, _x.io_fb_unlock, _x.io_fb_lower_beam_headlamp, _x.io_fb_upper_beam_headlamp, _x.io_fb_turn_lamp, _x.io_fb_braking_lamp, _x.io_fb_clearance_lamp, _x.io_fb_fog_lamp, _x.io_fb_speaker, _x.io_fb_fl_impact_sensor, _x.io_fb_fm_impact_sensor, _x.io_fb_fr_impact_sensor, _x.io_fb_rl_impact_sensor, _x.io_fb_rm_impact_sensor, _x.io_fb_rr_impact_sensor, _x.io_fb_fl_drop_sensor, _x.io_fb_fm_drop_sensor, _x.io_fb_fr_drop_sensor, _x.io_fb_rl_drop_sensor, _x.io_fb_rm_drop_sensor, _x.io_fb_rr_drop_sensor, _x.io_fb_estop, _x.io_fb_joypad_ctrl, _x.io_fb_charge_state,) = _get_struct_4Bb19B().unpack(str[start:end])
      self.io_fb_lamp_ctrl = bool(self.io_fb_lamp_ctrl)
      self.io_fb_unlock = bool(self.io_fb_unlock)
      self.io_fb_lower_beam_headlamp = bool(self.io_fb_lower_beam_headlamp)
      self.io_fb_upper_beam_headlamp = bool(self.io_fb_upper_beam_headlamp)
      self.io_fb_braking_lamp = bool(self.io_fb_braking_lamp)
      self.io_fb_clearance_lamp = bool(self.io_fb_clearance_lamp)
      self.io_fb_fog_lamp = bool(self.io_fb_fog_lamp)
      self.io_fb_speaker = bool(self.io_fb_speaker)
      self.io_fb_fl_impact_sensor = bool(self.io_fb_fl_impact_sensor)
      self.io_fb_fm_impact_sensor = bool(self.io_fb_fm_impact_sensor)
      self.io_fb_fr_impact_sensor = bool(self.io_fb_fr_impact_sensor)
      self.io_fb_rl_impact_sensor = bool(self.io_fb_rl_impact_sensor)
      self.io_fb_rm_impact_sensor = bool(self.io_fb_rm_impact_sensor)
      self.io_fb_rr_impact_sensor = bool(self.io_fb_rr_impact_sensor)
      self.io_fb_fl_drop_sensor = bool(self.io_fb_fl_drop_sensor)
      self.io_fb_fm_drop_sensor = bool(self.io_fb_fm_drop_sensor)
      self.io_fb_fr_drop_sensor = bool(self.io_fb_fr_drop_sensor)
      self.io_fb_rl_drop_sensor = bool(self.io_fb_rl_drop_sensor)
      self.io_fb_rm_drop_sensor = bool(self.io_fb_rm_drop_sensor)
      self.io_fb_rr_drop_sensor = bool(self.io_fb_rr_drop_sensor)
      self.io_fb_estop = bool(self.io_fb_estop)
      self.io_fb_joypad_ctrl = bool(self.io_fb_joypad_ctrl)
      self.io_fb_charge_state = bool(self.io_fb_charge_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4Bb19B = None
def _get_struct_4Bb19B():
    global _struct_4Bb19B
    if _struct_4Bb19B is None:
        _struct_4Bb19B = struct.Struct("<4Bb19B")
    return _struct_4Bb19B
