
(cl:in-package :asdf)

(defsystem "yhs_can_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "bms_fb" :depends-on ("_package_bms_fb"))
    (:file "_package_bms_fb" :depends-on ("_package"))
    (:file "bms_flag_fb" :depends-on ("_package_bms_flag_fb"))
    (:file "_package_bms_flag_fb" :depends-on ("_package"))
    (:file "ctrl_cmd" :depends-on ("_package_ctrl_cmd"))
    (:file "_package_ctrl_cmd" :depends-on ("_package"))
    (:file "ctrl_fb" :depends-on ("_package_ctrl_fb"))
    (:file "_package_ctrl_fb" :depends-on ("_package"))
    (:file "front_angle_fb" :depends-on ("_package_front_angle_fb"))
    (:file "_package_front_angle_fb" :depends-on ("_package"))
    (:file "io_cmd" :depends-on ("_package_io_cmd"))
    (:file "_package_io_cmd" :depends-on ("_package"))
    (:file "io_fb" :depends-on ("_package_io_fb"))
    (:file "_package_io_fb" :depends-on ("_package"))
    (:file "lf_wheel_fb" :depends-on ("_package_lf_wheel_fb"))
    (:file "_package_lf_wheel_fb" :depends-on ("_package"))
    (:file "lr_wheel_fb" :depends-on ("_package_lr_wheel_fb"))
    (:file "_package_lr_wheel_fb" :depends-on ("_package"))
    (:file "rear_angle_fb" :depends-on ("_package_rear_angle_fb"))
    (:file "_package_rear_angle_fb" :depends-on ("_package"))
    (:file "rf_wheel_fb" :depends-on ("_package_rf_wheel_fb"))
    (:file "_package_rf_wheel_fb" :depends-on ("_package"))
    (:file "rr_wheel_fb" :depends-on ("_package_rr_wheel_fb"))
    (:file "_package_rr_wheel_fb" :depends-on ("_package"))
    (:file "steering_ctrl_cmd" :depends-on ("_package_steering_ctrl_cmd"))
    (:file "_package_steering_ctrl_cmd" :depends-on ("_package"))
    (:file "steering_ctrl_fb" :depends-on ("_package_steering_ctrl_fb"))
    (:file "_package_steering_ctrl_fb" :depends-on ("_package"))
  ))