// Generated by gencpp from file yhs_can_msgs/steering_ctrl_cmd.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_STEERING_CTRL_CMD_H
#define YHS_CAN_MSGS_MESSAGE_STEERING_CTRL_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct steering_ctrl_cmd_
{
  typedef steering_ctrl_cmd_<ContainerAllocator> Type;

  steering_ctrl_cmd_()
    : ctrl_cmd_gear(0)
    , steering_ctrl_cmd_velocity(0.0)
    , steering_ctrl_cmd_steering(0.0)  {
    }
  steering_ctrl_cmd_(const ContainerAllocator& _alloc)
    : ctrl_cmd_gear(0)
    , steering_ctrl_cmd_velocity(0.0)
    , steering_ctrl_cmd_steering(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ctrl_cmd_gear_type;
  _ctrl_cmd_gear_type ctrl_cmd_gear;

   typedef float _steering_ctrl_cmd_velocity_type;
  _steering_ctrl_cmd_velocity_type steering_ctrl_cmd_velocity;

   typedef float _steering_ctrl_cmd_steering_type;
  _steering_ctrl_cmd_steering_type steering_ctrl_cmd_steering;





  typedef boost::shared_ptr< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct steering_ctrl_cmd_

typedef ::yhs_can_msgs::steering_ctrl_cmd_<std::allocator<void> > steering_ctrl_cmd;

typedef boost::shared_ptr< ::yhs_can_msgs::steering_ctrl_cmd > steering_ctrl_cmdPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::steering_ctrl_cmd const> steering_ctrl_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.ctrl_cmd_gear == rhs.ctrl_cmd_gear &&
    lhs.steering_ctrl_cmd_velocity == rhs.steering_ctrl_cmd_velocity &&
    lhs.steering_ctrl_cmd_steering == rhs.steering_ctrl_cmd_steering;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8e9d8788608c044b8a724447419e8d0";
  }

  static const char* value(const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8e9d8788608c044ULL;
  static const uint64_t static_value2 = 0xb8a724447419e8d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/steering_ctrl_cmd";
  }

  static const char* value(const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8    ctrl_cmd_gear\n"
"float32  steering_ctrl_cmd_velocity\n"
"float32  steering_ctrl_cmd_steering\n"
;
  }

  static const char* value(const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ctrl_cmd_gear);
      stream.next(m.steering_ctrl_cmd_velocity);
      stream.next(m.steering_ctrl_cmd_steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct steering_ctrl_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::steering_ctrl_cmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ctrl_cmd_gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ctrl_cmd_gear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_ctrl_cmd_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.steering_ctrl_cmd_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_ctrl_cmd_steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering_ctrl_cmd_steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_STEERING_CTRL_CMD_H
