// Generated by gencpp from file yhs_can_msgs/ctrl_fb.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_CTRL_FB_H
#define YHS_CAN_MSGS_MESSAGE_CTRL_FB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct ctrl_fb_
{
  typedef ctrl_fb_<ContainerAllocator> Type;

  ctrl_fb_()
    : ctrl_fb_gear(0)
    , ctrl_fb_x_linear(0.0)
    , ctrl_fb_z_angular(0.0)
    , ctrl_fb_y_linear(0.0)  {
    }
  ctrl_fb_(const ContainerAllocator& _alloc)
    : ctrl_fb_gear(0)
    , ctrl_fb_x_linear(0.0)
    , ctrl_fb_z_angular(0.0)
    , ctrl_fb_y_linear(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ctrl_fb_gear_type;
  _ctrl_fb_gear_type ctrl_fb_gear;

   typedef float _ctrl_fb_x_linear_type;
  _ctrl_fb_x_linear_type ctrl_fb_x_linear;

   typedef float _ctrl_fb_z_angular_type;
  _ctrl_fb_z_angular_type ctrl_fb_z_angular;

   typedef float _ctrl_fb_y_linear_type;
  _ctrl_fb_y_linear_type ctrl_fb_y_linear;





  typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const> ConstPtr;

}; // struct ctrl_fb_

typedef ::yhs_can_msgs::ctrl_fb_<std::allocator<void> > ctrl_fb;

typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb > ctrl_fbPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::ctrl_fb const> ctrl_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator2> & rhs)
{
  return lhs.ctrl_fb_gear == rhs.ctrl_fb_gear &&
    lhs.ctrl_fb_x_linear == rhs.ctrl_fb_x_linear &&
    lhs.ctrl_fb_z_angular == rhs.ctrl_fb_z_angular &&
    lhs.ctrl_fb_y_linear == rhs.ctrl_fb_y_linear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86ae5f105a87463279e4fc516204468c";
  }

  static const char* value(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86ae5f105a874632ULL;
  static const uint64_t static_value2 = 0x79e4fc516204468cULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/ctrl_fb";
  }

  static const char* value(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8    ctrl_fb_gear\n"
"float32  ctrl_fb_x_linear\n"
"float32  ctrl_fb_z_angular\n"
"float32  ctrl_fb_y_linear\n"
;
  }

  static const char* value(const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ctrl_fb_gear);
      stream.next(m.ctrl_fb_x_linear);
      stream.next(m.ctrl_fb_z_angular);
      stream.next(m.ctrl_fb_y_linear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ctrl_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::ctrl_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::ctrl_fb_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ctrl_fb_gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ctrl_fb_gear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ctrl_fb_x_linear: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_fb_x_linear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ctrl_fb_z_angular: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_fb_z_angular);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ctrl_fb_y_linear: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_fb_y_linear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_CTRL_FB_H
