// Generated by gencpp from file yhs_can_msgs/io_fb.msg
// DO NOT EDIT!


#ifndef YHS_CAN_MSGS_MESSAGE_IO_FB_H
#define YHS_CAN_MSGS_MESSAGE_IO_FB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_can_msgs
{
template <class ContainerAllocator>
struct io_fb_
{
  typedef io_fb_<ContainerAllocator> Type;

  io_fb_()
    : io_fb_lamp_ctrl(false)
    , io_fb_unlock(false)
    , io_fb_lower_beam_headlamp(false)
    , io_fb_upper_beam_headlamp(false)
    , io_fb_turn_lamp(0)
    , io_fb_braking_lamp(false)
    , io_fb_clearance_lamp(false)
    , io_fb_fog_lamp(false)
    , io_fb_speaker(false)
    , io_fb_fl_impact_sensor(false)
    , io_fb_fm_impact_sensor(false)
    , io_fb_fr_impact_sensor(false)
    , io_fb_rl_impact_sensor(false)
    , io_fb_rm_impact_sensor(false)
    , io_fb_rr_impact_sensor(false)
    , io_fb_fl_drop_sensor(false)
    , io_fb_fm_drop_sensor(false)
    , io_fb_fr_drop_sensor(false)
    , io_fb_rl_drop_sensor(false)
    , io_fb_rm_drop_sensor(false)
    , io_fb_rr_drop_sensor(false)
    , io_fb_estop(false)
    , io_fb_joypad_ctrl(false)
    , io_fb_charge_state(false)  {
    }
  io_fb_(const ContainerAllocator& _alloc)
    : io_fb_lamp_ctrl(false)
    , io_fb_unlock(false)
    , io_fb_lower_beam_headlamp(false)
    , io_fb_upper_beam_headlamp(false)
    , io_fb_turn_lamp(0)
    , io_fb_braking_lamp(false)
    , io_fb_clearance_lamp(false)
    , io_fb_fog_lamp(false)
    , io_fb_speaker(false)
    , io_fb_fl_impact_sensor(false)
    , io_fb_fm_impact_sensor(false)
    , io_fb_fr_impact_sensor(false)
    , io_fb_rl_impact_sensor(false)
    , io_fb_rm_impact_sensor(false)
    , io_fb_rr_impact_sensor(false)
    , io_fb_fl_drop_sensor(false)
    , io_fb_fm_drop_sensor(false)
    , io_fb_fr_drop_sensor(false)
    , io_fb_rl_drop_sensor(false)
    , io_fb_rm_drop_sensor(false)
    , io_fb_rr_drop_sensor(false)
    , io_fb_estop(false)
    , io_fb_joypad_ctrl(false)
    , io_fb_charge_state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _io_fb_lamp_ctrl_type;
  _io_fb_lamp_ctrl_type io_fb_lamp_ctrl;

   typedef uint8_t _io_fb_unlock_type;
  _io_fb_unlock_type io_fb_unlock;

   typedef uint8_t _io_fb_lower_beam_headlamp_type;
  _io_fb_lower_beam_headlamp_type io_fb_lower_beam_headlamp;

   typedef uint8_t _io_fb_upper_beam_headlamp_type;
  _io_fb_upper_beam_headlamp_type io_fb_upper_beam_headlamp;

   typedef int8_t _io_fb_turn_lamp_type;
  _io_fb_turn_lamp_type io_fb_turn_lamp;

   typedef uint8_t _io_fb_braking_lamp_type;
  _io_fb_braking_lamp_type io_fb_braking_lamp;

   typedef uint8_t _io_fb_clearance_lamp_type;
  _io_fb_clearance_lamp_type io_fb_clearance_lamp;

   typedef uint8_t _io_fb_fog_lamp_type;
  _io_fb_fog_lamp_type io_fb_fog_lamp;

   typedef uint8_t _io_fb_speaker_type;
  _io_fb_speaker_type io_fb_speaker;

   typedef uint8_t _io_fb_fl_impact_sensor_type;
  _io_fb_fl_impact_sensor_type io_fb_fl_impact_sensor;

   typedef uint8_t _io_fb_fm_impact_sensor_type;
  _io_fb_fm_impact_sensor_type io_fb_fm_impact_sensor;

   typedef uint8_t _io_fb_fr_impact_sensor_type;
  _io_fb_fr_impact_sensor_type io_fb_fr_impact_sensor;

   typedef uint8_t _io_fb_rl_impact_sensor_type;
  _io_fb_rl_impact_sensor_type io_fb_rl_impact_sensor;

   typedef uint8_t _io_fb_rm_impact_sensor_type;
  _io_fb_rm_impact_sensor_type io_fb_rm_impact_sensor;

   typedef uint8_t _io_fb_rr_impact_sensor_type;
  _io_fb_rr_impact_sensor_type io_fb_rr_impact_sensor;

   typedef uint8_t _io_fb_fl_drop_sensor_type;
  _io_fb_fl_drop_sensor_type io_fb_fl_drop_sensor;

   typedef uint8_t _io_fb_fm_drop_sensor_type;
  _io_fb_fm_drop_sensor_type io_fb_fm_drop_sensor;

   typedef uint8_t _io_fb_fr_drop_sensor_type;
  _io_fb_fr_drop_sensor_type io_fb_fr_drop_sensor;

   typedef uint8_t _io_fb_rl_drop_sensor_type;
  _io_fb_rl_drop_sensor_type io_fb_rl_drop_sensor;

   typedef uint8_t _io_fb_rm_drop_sensor_type;
  _io_fb_rm_drop_sensor_type io_fb_rm_drop_sensor;

   typedef uint8_t _io_fb_rr_drop_sensor_type;
  _io_fb_rr_drop_sensor_type io_fb_rr_drop_sensor;

   typedef uint8_t _io_fb_estop_type;
  _io_fb_estop_type io_fb_estop;

   typedef uint8_t _io_fb_joypad_ctrl_type;
  _io_fb_joypad_ctrl_type io_fb_joypad_ctrl;

   typedef uint8_t _io_fb_charge_state_type;
  _io_fb_charge_state_type io_fb_charge_state;





  typedef boost::shared_ptr< ::yhs_can_msgs::io_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_can_msgs::io_fb_<ContainerAllocator> const> ConstPtr;

}; // struct io_fb_

typedef ::yhs_can_msgs::io_fb_<std::allocator<void> > io_fb;

typedef boost::shared_ptr< ::yhs_can_msgs::io_fb > io_fbPtr;
typedef boost::shared_ptr< ::yhs_can_msgs::io_fb const> io_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_can_msgs::io_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_can_msgs::io_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yhs_can_msgs::io_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::io_fb_<ContainerAllocator2> & rhs)
{
  return lhs.io_fb_lamp_ctrl == rhs.io_fb_lamp_ctrl &&
    lhs.io_fb_unlock == rhs.io_fb_unlock &&
    lhs.io_fb_lower_beam_headlamp == rhs.io_fb_lower_beam_headlamp &&
    lhs.io_fb_upper_beam_headlamp == rhs.io_fb_upper_beam_headlamp &&
    lhs.io_fb_turn_lamp == rhs.io_fb_turn_lamp &&
    lhs.io_fb_braking_lamp == rhs.io_fb_braking_lamp &&
    lhs.io_fb_clearance_lamp == rhs.io_fb_clearance_lamp &&
    lhs.io_fb_fog_lamp == rhs.io_fb_fog_lamp &&
    lhs.io_fb_speaker == rhs.io_fb_speaker &&
    lhs.io_fb_fl_impact_sensor == rhs.io_fb_fl_impact_sensor &&
    lhs.io_fb_fm_impact_sensor == rhs.io_fb_fm_impact_sensor &&
    lhs.io_fb_fr_impact_sensor == rhs.io_fb_fr_impact_sensor &&
    lhs.io_fb_rl_impact_sensor == rhs.io_fb_rl_impact_sensor &&
    lhs.io_fb_rm_impact_sensor == rhs.io_fb_rm_impact_sensor &&
    lhs.io_fb_rr_impact_sensor == rhs.io_fb_rr_impact_sensor &&
    lhs.io_fb_fl_drop_sensor == rhs.io_fb_fl_drop_sensor &&
    lhs.io_fb_fm_drop_sensor == rhs.io_fb_fm_drop_sensor &&
    lhs.io_fb_fr_drop_sensor == rhs.io_fb_fr_drop_sensor &&
    lhs.io_fb_rl_drop_sensor == rhs.io_fb_rl_drop_sensor &&
    lhs.io_fb_rm_drop_sensor == rhs.io_fb_rm_drop_sensor &&
    lhs.io_fb_rr_drop_sensor == rhs.io_fb_rr_drop_sensor &&
    lhs.io_fb_estop == rhs.io_fb_estop &&
    lhs.io_fb_joypad_ctrl == rhs.io_fb_joypad_ctrl &&
    lhs.io_fb_charge_state == rhs.io_fb_charge_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yhs_can_msgs::io_fb_<ContainerAllocator1> & lhs, const ::yhs_can_msgs::io_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yhs_can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_can_msgs::io_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_can_msgs::io_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_can_msgs::io_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "734f5c2c489a056cd36d8e25d62c72df";
  }

  static const char* value(const ::yhs_can_msgs::io_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x734f5c2c489a056cULL;
  static const uint64_t static_value2 = 0xd36d8e25d62c72dfULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_can_msgs/io_fb";
  }

  static const char* value(const ::yhs_can_msgs::io_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  io_fb_lamp_ctrl\n"
"bool  io_fb_unlock\n"
"bool  io_fb_lower_beam_headlamp\n"
"bool  io_fb_upper_beam_headlamp\n"
"int8  io_fb_turn_lamp\n"
"bool  io_fb_braking_lamp\n"
"bool  io_fb_clearance_lamp\n"
"bool  io_fb_fog_lamp\n"
"bool  io_fb_speaker\n"
"bool  io_fb_fl_impact_sensor\n"
"bool  io_fb_fm_impact_sensor\n"
"bool  io_fb_fr_impact_sensor\n"
"bool  io_fb_rl_impact_sensor\n"
"bool  io_fb_rm_impact_sensor\n"
"bool  io_fb_rr_impact_sensor\n"
"bool  io_fb_fl_drop_sensor\n"
"bool  io_fb_fm_drop_sensor\n"
"bool  io_fb_fr_drop_sensor\n"
"bool  io_fb_rl_drop_sensor\n"
"bool  io_fb_rm_drop_sensor\n"
"bool  io_fb_rr_drop_sensor\n"
"bool  io_fb_estop\n"
"bool  io_fb_joypad_ctrl\n"
"bool  io_fb_charge_state\n"
;
  }

  static const char* value(const ::yhs_can_msgs::io_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.io_fb_lamp_ctrl);
      stream.next(m.io_fb_unlock);
      stream.next(m.io_fb_lower_beam_headlamp);
      stream.next(m.io_fb_upper_beam_headlamp);
      stream.next(m.io_fb_turn_lamp);
      stream.next(m.io_fb_braking_lamp);
      stream.next(m.io_fb_clearance_lamp);
      stream.next(m.io_fb_fog_lamp);
      stream.next(m.io_fb_speaker);
      stream.next(m.io_fb_fl_impact_sensor);
      stream.next(m.io_fb_fm_impact_sensor);
      stream.next(m.io_fb_fr_impact_sensor);
      stream.next(m.io_fb_rl_impact_sensor);
      stream.next(m.io_fb_rm_impact_sensor);
      stream.next(m.io_fb_rr_impact_sensor);
      stream.next(m.io_fb_fl_drop_sensor);
      stream.next(m.io_fb_fm_drop_sensor);
      stream.next(m.io_fb_fr_drop_sensor);
      stream.next(m.io_fb_rl_drop_sensor);
      stream.next(m.io_fb_rm_drop_sensor);
      stream.next(m.io_fb_rr_drop_sensor);
      stream.next(m.io_fb_estop);
      stream.next(m.io_fb_joypad_ctrl);
      stream.next(m.io_fb_charge_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct io_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_can_msgs::io_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_can_msgs::io_fb_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_lamp_ctrl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_lamp_ctrl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_unlock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_unlock);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_lower_beam_headlamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_lower_beam_headlamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_upper_beam_headlamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_upper_beam_headlamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_turn_lamp: ";
    Printer<int8_t>::stream(s, indent + "  ", v.io_fb_turn_lamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_braking_lamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_braking_lamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_clearance_lamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_clearance_lamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_fog_lamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fog_lamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_speaker: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_speaker);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_fl_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fl_impact_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_fm_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fm_impact_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_fr_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fr_impact_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_rl_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_rl_impact_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_rm_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_rm_impact_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_rr_impact_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_rr_impact_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_fl_drop_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fl_drop_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_fm_drop_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fm_drop_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_fr_drop_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_fr_drop_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_rl_drop_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_rl_drop_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_rm_drop_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_rm_drop_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_rr_drop_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_rr_drop_sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_estop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_estop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_joypad_ctrl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_joypad_ctrl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "io_fb_charge_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_fb_charge_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_CAN_MSGS_MESSAGE_IO_FB_H
